### PR TITLE
Added a handbook folder and added in a skeleton of how I want the ha…

### PR DESCRIPTION
**Pull request by rsbaek**
…ndbook to end up looking. Currently working on general bullet points to discuss in each subtopic, and will have a final product ready soon.

### CODE REVIEW

**Comment by ErikBoesen** [comment]
Now I'm going to merge the pull request and that will put your changes into the main repository. If necessary, we could discuss and deliberate your changes, but we don't need to in this case.

**Comment by CarterFendley** [comment]
For future reference try not to add files such as ".DS_STORE"

**Comment by rsbaek** [comment]
Noted. Thanks for the tip!

**Comment by ErikBoesen** [comment]
@CarterFendley I'll add a gitignore, one second.

**Pull request merged**
